/**
 * api.js
 *
 * This is the ONLY file that talks to the backend over the network.
 *
 * Why this file exists:
 * The technical spec defines exactly one endpoint, POST /api/interview,
 * used in two different "modes" (start a session / continue a session).
 * Instead of writing fetch() calls inside app.js wherever a button is
 * clicked, every part of the UI that needs backend data calls one of
 * the two functions below. If the API contract or base URL ever
 * changes, this is the only file that needs to change.
 *
 * Both functions return a Promise that resolves to the parsed JSON
 * response ({ reply, done, feedback? }), or throws an ApiError with a
 * human-readable message the UI can show directly.
 */

// Auto-detect API URL: if on separate static dev port (5500/5173/3000), point to 8000;
// otherwise use current origin (for production deployment and single-server run).
const API_BASE_URL = (typeof window !== "undefined" && window.location && window.location.port && ["5500", "5173", "3000"].includes(window.location.port))
  ? "http://127.0.0.1:8000"
  : (typeof window !== "undefined" && window.location ? window.location.origin : "http://127.0.0.1:8000");

/**
 * Thrown whenever a call to the backend fails, for any reason
 * (network down, bad request, session not found, server error). Every
 * instance carries a `friendlyMessage` that's already safe and clear
 * enough to show directly in the UI - callers never need to inspect
 * status codes themselves.
 */
class ApiError extends Error {
  constructor(friendlyMessage, status) {
    super(friendlyMessage);
    this.name = "ApiError";
    this.friendlyMessage = friendlyMessage;
    this.status = status || null;
  }
}

/**
 * Shared helper: POST a JSON body to /api/interview and turn any
 * failure (network error, non-2xx status, malformed JSON) into a
 * single ApiError with a friendly message.
 */
async function postInterview(body) {
  let response;
  try {
    response = await fetch(`${API_BASE_URL}/api/interview`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    });
  } catch (networkError) {
    throw new ApiError(
      "Couldn't reach the interview server. Check that the backend is running and try again."
    );
  }

  let payload = null;
  try {
    payload = await response.json();
  } catch (parseError) {
    // A non-JSON body is unusual but shouldn't crash the UI.
    payload = null;
  }

  if (!response.ok) {
    const detail = payload && payload.detail ? payload.detail : null;

    if (response.status === 404) {
      throw new ApiError(
        detail || "This interview session couldn't be found. Start a new interview.",
        404
      );
    }
    if (response.status === 409) {
      throw new ApiError(
        detail || "A session with this ID already exists.",
        409
      );
    }
    if (response.status === 400) {
      throw new ApiError(detail || "That request wasn't valid. Please try again.", 400);
    }
    if (response.status === 502) {
      throw new ApiError(
        detail || "The AI interviewer had trouble responding. Please try again.",
        502
      );
    }
    throw new ApiError(
      detail || "Something went wrong talking to the interview server.",
      response.status
    );
  }

  return payload;
}

/**
 * Start a brand-new interview session.
 *
 * @param {string} sessionId - a fresh id generated by the frontend.
 * @param {object} candidate - the full candidate object (matches
 *   candidate.json's schema), taken directly from the roster the
 *   candidate was picked from.
 * @returns {Promise<{reply: string, done: boolean}>}
 */
async function startInterview(sessionId, candidate) {
  return postInterview({ sessionId, candidate });
}

/**
 * Continue an existing interview session with the candidate's latest
 * answer.
 *
 * @param {string} sessionId - the same id used to start the interview.
 * @param {string} message - the candidate's answer text.
 * @returns {Promise<{reply: string, done: boolean, feedback?: object}>}
 */
async function continueInterview(sessionId, message) {
  return postInterview({ sessionId, message });
}
